#!/usr/bin/env bash

set -euo pipefail

globalDir="$(cd "$(dirname "${0}")/../../" && pwd)"
localDir="$(git rev-parse --show-superproject-working-tree --show-toplevel | head -1)"

secretlintrc() {
  for fmt in yaml json js; do
    if test -e "${localDir}/.secrentlintrc.${fmt}"; then
      echo "${localDir}/.secretlintrc.${fmt}"
      return 0
    fi
  done

  if test -e "${localDir}/.secrentlintrc"; then
    echo "${localDir}/.secretlintrc"
    return 0   
  fi

  echo "${globalDir}/secretlintrc.json"
  return 0
}

secretlintignore() {
  if test -e "${localDir}/.secrentlintignore"; then
    echo "${localDir}/.secrentlintignore"
    return 0
  fi
}

args() {
  local args="--secretlintrc $(secretlintrc)"
  local ignore="$(secretlintignore)"

  if test "x${ignore}" != "x"; then
    args="${args} --secrentlintignore ${ignore}"
  fi

  echo $args
  return 0
}

main() {
  local files=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

  if test ! -z "${files}"; then
    echo $files | xargs "${globalDir}/node_modules/.bin/secretlint" $(args)

    if test $? -ne 0; then
      echo "this commit contain secret credentials"
      return 1
    fi
  fi

  return 0
}

main "${@}"
