#!/usr/bin/env bash

set -euo pipefail

ROOTDIR="$(cd "$(dirname "${0}")/../../" && pwd)"
REPODIR="$(git rev-parse --show-superproject-working-tree --show-toplevel | head -1)"

secretlintrc() {
  for fmt in yaml json js; do
    if [[ -e "${REPODIR}/.secretlintrc.${fmt}" ]]; then
      echo "${REPODIR}/.secretlintrc.${fmt}"
      return 0
    fi
  done

  if [[ -e "${REPODIR}/.secretlintrc" ]]; then
    echo "${REPODIR}/.secretlintrc"
    return 0
  fi

  echo "${ROOTDIR}/secretlintrc.json"
  return 0
}

secretlintignore() {
  if [[ -e "${REPODIR}/.secretlintignore" ]]; then
    echo "${REPODIR}/.secretlintignore"
    return 0
  fi

  echo "${ROOTDIR}/secretlintignore"
  return 0
}

main() {
  export NODE_PATH="${ROOTDIR}/node_modules"
  export PATH=${NODE_PATH}/.bin:$PATH

  git diff --cached --name-only --diff-filter=ACMR \
    | xargs -P"$(nproc --all --ignore 1)" -I{} secretlint --secretlintignore "$(secretlintignore)" --secretlintrc "$(secretlintrc)" "${REPODIR}/{}"

  return $?
}

main "${@}"
