#!/usr/bin/env bash

set -euo pipefail

ROOTDIR="$(cd "$(dirname "${0}")/../" && pwd)"
REPODIR="$(git rev-parse --show-superproject-working-tree --show-toplevel | head -1)"

disabled() {
  local action="${1}"
  [[ -e "${REPODIR}/.git/hooks/.disable-action-${action}" ]] \
    || [[ -e "${REPODIR}/.githooks/.disable-action-${action}" ]]
}

main() {
  if [[ -e "${REPODIR}/.git/hooks/pre-commit" ]]; then
    "${REPODIR}/.git/hooks/pre-commit" "${@}"
    return $?
  fi

  for action in "${ROOTDIR}"/actions/pre-commit/*; do
    if ! disabled "$(basename "${action}")" ; then
      "${action}" "${@}" || return $?
    fi
  done

  return 0
}

main "${@}"
