#!/usr/bin/env bash

set -euo pipefail

ROOTDIR="$(cd "$(dirname "${0}")/../../" && pwd)"
REPODIR="$(git rev-parse --show-superproject-working-tree --show-toplevel | head -1)"

commitlintrc() {
  for fmt in json yaml yml js cjs mjs ts cts ; do
    if [[ -e "${REPODIR}/.commitlintrc.${fmt}" ]]; then
      echo "${REPODIR}/.commitlintrc.${fmt}"
      return 0
    fi
  done

  for fmt in js cjs ts cts ; do
    if [[ -e "${REPODIR}/commitlint.config.${fmt}" ]]; then
      echo "${REPODIR}/commitlint.config.${fmt}"
      return 0
    fi
  done

  if [[ -e "${REPODIR}/.commitlintrc" ]]; then
    echo "${REPODIR}/.commitlintrc"
    return 0
  fi

  if [[ -e "${REPODIR}/package.json" ]] \
    && grep '"commitlint":' "${REPODIR}/package.json" ; then
    return 0
  fi

  echo "${ROOTDIR}/commitlintrc.json"
  return 0
}

main() {
  local msg="${1}"
  export NODE_PATH="${ROOTDIR}/node_modules"
  export PATH=${NODE_PATH}/.bin:$PATH
  
  commitlint --config "$(commitlintrc)" --edit "${msg}"
  return $?
}

main "${@}"
